import { config } from 'dotenv';
config({ path: `.env` });

export const CREDENTIALS = process.env.CREDENTIALS === 'true';

export const {
	PORT,
	SECRET_KEY,
    LOG_DIR,
	BASE_PATH,
	ORIGIN,
	LOG_FORMAT,
	NODE_ENV,
	FIREBASE_API_KEY,
	FIREBASE_AUTH_DOMAIN,
	FIREBASE_PROJECT_ID,
	FIREBASE_STORAGE_BUCKET,
	FIREBASE_MESSAGING_SENDER_ID,
	FIREBASE_APP_ID,
	FIREBASE_MEASUREMENT_ID,
	RAZORPAY_KEY_SECRET,
    RAZORPAY_KEY_ID,
} = process.env;
